name = "valuenodetest"
account_id = "139bb1df28f22946e59b30be45a09fdd"
workers_dev = true
compatibility_date = "2025-03-04"
main = "workers-site/index.js"  # if using a custom worker
[site]
bucket = "./dist"   
